### ISSUE TITLE
Validation of composed models as body parameters doesn't work

### ISSUE THREAD

**Issue by tomtit** [swagger-api/swagger-inflector#111]
I added two tests to demonstrate the issue on my [fork](https://github.com/tomtit/swagger-inflector/tree/composed-model-validation).
1. Inflector allows passing of [composite](https://github.com/tomtit/swagger-inflector/blob/composed-model-validation/src/test/swagger/sample1.yaml#L848-L858) models without required properties - check this [test](https://github.com/tomtit/swagger-inflector/blob/composed-model-validation/src/test/java/io/swagger/test/integration/RequestTestIT.java#L75-L80)
2. Uncomment this [request](https://github.com/tomtit/swagger-inflector/blob/composed-model-validation/src/test/swagger/sample1.yaml#L628-L641) for the next issue. Inflector initialization fails with NPE when array of objects having composite model is passed as a body parameter.

**Comment by olensmar** [comment]
@tomtit is this still an issue with all the changes since you reported it?

**Comment by tomtit** [comment]
Both issues still present (the fork was rebased before checking)

**Comment by olensmar** [comment]
ok thanks @tomtit  - @fehguy @webron is this on your radar?

**Comment by fehguy** [comment]
On my radar, meaning am I fixing it?  If there's no urgency associated with the issue, then likely no, I'm not.

for item 1 I assume you're not running the server with `validatePayloads` are you?  I hope not...

For item 2 it sounds like a parser issue.  I can see if that can be addressed by updating to v1.0.29.

**Comment by fehguy** [comment]
@tomtit please try v1.0.13

**Comment by olensmar** [comment]
thanks @fehguy for the quick turn-around - will let you know asap
