### ISSUE TITLE
Project naming: is "swagger-inflector"

### ISSUE THREAD

**Issue by earth2marsh** [swagger-api/swagger-inflector#12]
With swagger-node, the idea was to make it very clear that it was the project for building APIs using Swagger and Node. 

On the Java side, there are `swagger-codegen`, `swagger-core`, and probably others, but there's additional processing that potential users must do in order to understand what the purpose of the project is. Yes, that can be handled in the description or readme, but assuming there are other swagger-server-frameworks in other languages, having consistent naming across all projects seems important (and may imply `swagger-node` isn't quite the right name either).

Is `swagger-inflector` meaningful enough to potential adopters? Or is it a name that has more to do with how it relates to existing Java-based Swagger projects?

**Comment by fehguy** [comment]
Being released, I'm going to close this out.  I am not married to the name so if we have trouble, we'll adjust!
