### ISSUE TITLE
inheritance using allOf not supported

### ISSUE THREAD

**Issue by resch78** [swagger-api/swagger-inflector#126]
using the allOf keyword results in an error

**Comment by fehguy** [comment]
`allOf` is supported but it's possible the way you're using it is not.  Please share your spec that is giving an error.

**Comment by resch78** [comment]
hi,

please see the attached masked yaml

[sample_swagger.yaml.txt](https://github.com/swagger-api/swagger-inflector/files/372179/sample_swagger.yaml.txt)
excerpt
