### ISSUE TITLE
integer type properties without format are not auto generated

### ISSUE THREAD

**Issue by resch78** [swagger-api/swagger-inflector#127]
integer type properties without format provided should default to int32

**Comment by fehguy** [comment]
Actually I believe BigDecimal is the expected type when no format is used. What do you see?

**Comment by resch78** [comment]
Wouldn't BigDecimal better suit a number type and BigInteger the integer type?

However, this is the response:

{
  "code": 400,
  "message": "Input error: query parameter `page value `1` is less or equal to the minimum allowed value `1.0`"
}
