### ISSUE TITLE
Set default output format to json for implemented methods

### ISSUE THREAD

**Issue by hni** [swagger-api/swagger-inflector#135]
I use swagger-inflector and swagger-codegen to create a java jersey2 app. All my unimplemented methods are mocked by inflector and return json. But the methods I implement return xml by default. The "@Produces" annotation on my implemented controller methods seems to be ignored. The only way to make them return json is to set the "Accept" header with every request. 

Controller class:

```
[...]
import javax.ws.rs.GET;
import javax.ws.rs.Produces;

public class CampaignController {

    @GET
    @Produces({"application/json"})
    public Campaign listCampaigns(RequestContext context, Long customerId){
        final Campaign campaign = new Campaign();
        campaign.setName("dodo");
        return campaign;
    }

}
```

Example requests:

Method I implemented, returns xml per default:
```

curl -s -H "Accept: application/json" http://104.155.88.210:8085/v1/customers/1/campaigns 
{"name":"dodo","callouts":[],"negativeKeywords":[]}



curl -s   http://104.155.88.210:8085/v1/customers/1/campaigns
<Campaign><id/><name>dodo</name><dailyBudget/><callouts/><startDate/><endDate/><partnerRadius/><negativeKeywords/><active/></Campaign>


```
Mocked method,  returns json even without "Accept" header:

```
curl -s   http://104.155.88.210:8085/v1/customers/1/campaigns/1

{"id":0,"name":"string","dailyBudget":0,"callouts":["string"],"startDate":"2015-07-20","endDate":"2015-07-20","partnerRadius":1.1,"negativeKeywords":["id"
0,"text","string"],"active":true}
```

**Comment by fehguy** [comment]
I cannot reproduce this.  Could you please see this test:

https://github.com/swagger-api/swagger-inflector/commit/86bc9237d30b9d5abf84aadd00d4409288d27816#diff-89a0c8077283ca65b420bbd7a195c5d2R103

And report back as to what is different?
