### ISSUE TITLE
Request validation

### ISSUE THREAD

**Issue by jasonh-n-austin** [swagger-api/swagger-inflector#16]
As Swagger defines models, types and formats (JSON Schema-based and custom), basic validation can be applied to requests. The status code would need to be configurable, `400` default would satisfy most APIs. 
Error response object definition would need to be customized through mapping the Swagger generated errors into a custom model.
Additionally, business logic validations would need to be easily merged with Swagger validations before response.

The problem solved: implementation matches spec in regards to type and format validation.

**Comment by krupa-n** [comment]
Would you mind sharing more details about the custom validation requirement?

**Comment by jasonh-n-austin** [comment]
When a reqeust parameters are defined, it's useful for an implementer if basic type validation of parameters/fields is taken care of. 
As Swagger defines parameters (esp. `body` + schema), sufficient data is available to provide validation. In cases where the request parameter does not match the parameter/schema in `swagger.json` (and/or linked schema), the controller should produce a `400` status code and an error object response.

**Comment by fehguy** [comment]
added support of serializable params.  Will add body param validation, then this can be closed.
