### ISSUE TITLE
Feature request: customization of Jackson

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-inflector#161]
For instance, joda or java.time dates in POJOs are not ser/deser'd correctly because jackson-datatype-jsr310 or jackson-datatype-joda modules are not registered so it would be useful to:
- either be able customize directly the existing objectMapper 
- or to be able to provide our own Provider for objectMapper
- or to have a mechanism to provide jackson modules to register

**Comment by damnhandy** [comment]
I've submitted a PR to allow for a user supplied ObjectMapper. In two different situations, we've got a global ObjectMapper instance already configured. It makes more sense to reuse that one rather that ensuring that the Swagger inflector ObjectMapper matches ours. 

The downside to my PR is that this doesn't work when configured via the ServletContext constructor. We're using SpringBoot and Akka, so relying on a servlet context isn't a priority at the moment. We'd be configuring the SwaggerInflector manually. You can see my [example here](https://github.com/swagger-api/swagger-samples/pull/67). Thus, my PR for this issue doesn't address customization when configured via servlet.

**Comment by fehguy** [comment]
@damnhandy I think it's fair to require some programmatic configuration for advanced features, such as overriding the objectmapper when using servlet configuration.
