### ISSUE TITLE
Not generating controllers?

### ISSUE THREAD

**Issue by SteveNewhouse** [swagger-api/swagger-inflector#164]
Hello there.  New to inflector, so pls bear with me.

I've got a sample project up and running.  I have made only very minor changes to the sample swagger spec and I am indeed seeing the generated model classes update, but I don't see any controller classes generated at all.

My questions are 1) does inflector generate stubbed controllers?  I thought that an older version I had seen most certainly did... and 2) if so, what should I look for to figure out why I'm not seeing any?

My inflector.yaml file is as follows:

```
controllerPackage: com.fakecorp.api.controllers
modelPackage: com.fakecorp.api.models
swaggerUrl: ./src/main/swagger/swagger.yaml

# add any model mappings you like if you have existing models to use
#modelMappings:
#  Pet: io.swagger.sample.models.Pet

entityProcessors:
  - json
  - xml

# set the environment to development | staging | production
environment: development
```
Note that even with the controller and model packages set as shown, the model classes still get generated under io.swagger.sample.models.

**Comment by webron** [comment]
Hi @SteveNewhouse - the inflector does *not* generate classes (unlike the codegen) - it dynamically binds to your own controllers, though they don't need to be regular JAX-RS resources. Check out the main README for more details on how the binding is actually done and what options you have to control it.

**Comment by SteveNewhouse** [comment]
Ah.. Pardon me.  I had got confused by issue https://github.com/swagger-api/swagger-inflector/issues/119 which referenced controller generation (but that was bc the OP added it)...
