### ISSUE TITLE
Composed models are deserialized as JsonNode after PR #191

### ISSUE THREAD

**Issue by tomtit** [swagger-api/swagger-inflector#193]
Composed models are deserialized as JsonNode after PR #191.
The test for the issue can be found on my [fork](https://github.com/tomtit/swagger-inflector/blob/composed-model-deserialization/src/test/java/io/swagger/test/integration/RequestTestIT.java#L102)
The call to the test end point fails due to invalid arguments: `java.lang.IllegalArgumentException: argument type mismatch`

**Comment by fehguy** [comment]
Please send a PR with failing tests

**Comment by tomtit** [comment]
I've dropped the fix from my PR #194 to have a PR with test only - PR #195

**Comment by olensmar** [comment]
@fehguy ping..!

**Comment by fehguy** [comment]
Fixed by https://github.com/swagger-api/swagger-inflector/commit/a638991587c9706450265a21cc94e37a1c777011

**Comment by fehguy** [comment]
@tomtit please try out 1.0.14-SNAPSHOT
