### ISSUE TITLE
Quick start has something wrong in centos7.3

### ISSUE THREAD

**Issue by bruceforlearn** [swagger-api/swagger-inflector#204]
I has create a new Centos7.3(3.10.0-514.26.2.el7.x86_64) VM for swagger-inflector, and then I run curl -L http://bit.ly/1Pl62pe | project=my-project bash

as you see "rm: cannot remove ‘pom.xml--’: No such file or directory"
[root@localhost swagger]# ./editor.sh
./editor.sh: line 1: mvn: command not found

@fehguy please help

thank you !

[root@localhost home]# mkdir swagger
[root@localhost home]# ls
swagger
[root@localhost home]# cd swagger/
[root@localhost swagger]# ls
[root@localhost swagger]# curl -L http://bit.ly/1Pl62pe | project=my-project bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   166  100   166    0     0    119      0  0:00:01  0:00:01 --:--:--   119
100  1971  100  1971    0     0    611      0  0:00:03  0:00:03 --:--:--  1638
...fetching editor webapp
...fetching editor scripts
...fetching sample swagger description
...fetching inflector configuration
...fetching project pom
...fetching web.xml
rm: cannot remove ‘pom.xml--’: No such file or directory
done!  You can run swagger editor as follows:
./editor.sh
then open a browser at open http://localhost:8000

you can run your server as follows:
mvn package jetty:run

and your swagger listing will be at http://localhost:8080/{basePath}/swagger.json

[root@localhost swagger]# ls
editor  editor.sh  inflector.yaml  pom.xml  src
[root@localhost swagger]# cat pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>5</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.swagger</groupId>
    <artifactId>my-project</artifactId>
    <packaging>jar</packaging>
    <name>my-project</name>
    <version>1.0.1</version>
    <prerequisites>
        <maven>2.2.0</maven>
    </prerequisites>
    <developers>
        <developer>
            <id>fehguy</id>
            <name>Tony Tam</name>
            <email>fehguy@gmail.com</email>
        </developer>
    </developers>
    <mailingLists>
        <mailingList>
            <name>swagger-swaggersocket</name>
            <archive>https://groups.google.com/forum/#!forum/swagger-swaggersocket</archive>
        </mailingList>
    </mailingLists>
    <licenses>
        <license>
            <name>Apache License 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <build>
        <defaultGoal>install</defaultGoal>
        <directory>target</directory>
        <finalName>${project.artifactId}-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.9.1</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/gen/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <excludes>
                        <exclude>**/logback.xml</exclude>
                    </excludes>
                    <archive>
                        <manifestEntries>
                            <mode>development</mode>
                            <url>${project.url}</url>
                            <implementation-version>${project.version}</implementation-version>
                            <package>io.swagger</package>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>${jetty-version}</version>
                <configuration>
                    <monitoredDirName>.</monitoredDirName>
                    <scanTargets>
                        <scanTarget>inflector.yaml</scanTarget>
                        <scanTarget>src/main/swagger/swagger.yaml</scanTarget>
                    </scanTargets>
                    <scanIntervalSeconds>1</scanIntervalSeconds>
                    <webApp>
                        <contextPath>/</contextPath>
                    </webApp>
                    <httpConnector>
                        <port>8080</port>
                        <idleTimeout>60000</idleTimeout>
                    </httpConnector>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        
        <profile>
            <id>pojos</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.swagger</groupId>
                        <artifactId>swagger-codegen-maven-plugin</artifactId>
                        <version>${codegen-version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <environmentVariables>
                                        
                                        <models></models>
                                        
                                        <supportingFiles>StringUtil.java</supportingFiles>
                                    </environmentVariables>
                                    <inputSpec>src/main/swagger/swagger.yaml</inputSpec>
                                    <language>java</language>
                                    <configOptions>
                                        <sourceFolder>src/gen/java</sourceFolder>
                                    </configOptions>
                                    <output>.</output>
                                    <modelPackage>io.swagger.sample.models</modelPackage>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    <dependencies>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-inflector</artifactId>
            <version>1.0.9</version>
        </dependency>
    </dependencies>
    <properties>
        <jetty-version>9.2.9.v20150224</jetty-version>
        <logback-version>1.0.1</logback-version>
        <junit-version>4.8.2</junit-version>
        <slf4j-version>1.6.3</slf4j-version>
        <codegen-version>2.1.4</codegen-version>
    </properties>
</project>
[root@localhost swagger]#
[root@localhost swagger]#
[root@localhost swagger]# ls
editor  editor.sh  inflector.yaml  pom.xml  src
[root@localhost swagger]# ./editor.sh
./editor.sh: line 1: mvn: command not found
[root@localhost swagger]#

**Comment by bruceforlearn** [comment]
@webron please help 
thank you

**Comment by bruceforlearn** [comment]
@damnhandy 
[ERROR] No plugin found for prefix 'jetty' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/root/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by bruceforlearn** [comment]
[WARNING] Failure to transfer org.apache.maven.plugins/maven-metadata.xml from h                                                                                             ttps://repo.maven.apache.org/maven2 was cached in the local repository, resoluti                                                                                             on will not be reattempted until the update interval of central has elapsed or u                                                                                             pdates are forced. Original error: Could not transfer metadata org.apache.maven.                                                                                             plugins/maven-metadata.xml from/to central (https://repo.maven.apache.org/maven2                                                                                             ): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.180.215]                                                                                              failed: Connection refused (Connection refused)
[WARNING] Failure to transfer org.codehaus.mojo/maven-metadata.xml from https://                                                                                             repo.maven.apache.org/maven2 was cached in the local repository, resolution will                                                                                              not be reattempted until the update interval of central has elapsed or updates                                                                                              are forced. Original error: Could not transfer metadata org.codehaus.mojo/maven-                                                                                             metadata.xml from/to central (https://repo.maven.apache.org/maven2): Connect to                                                                                              repo.maven.apache.org:443 [repo.maven.apache.org/151.101.180.215] failed: Connec                                                                                             tion refused (Connection refused)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:58 min
[INFO] Finished at: 2017-09-12T11:15:12+08:00
[INFO] Final Memory: 9M/102M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'jetty' in the current project and in the plu                                                                                             gin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repo                                                                                             sitories [local (/root/.m2/repository), central (https://repo.maven.apache.org/m                                                                                             aven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                                                             ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                                                             d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundF                                                                                             orPrefixException

**Comment by bruceforlearn** [comment]
[root@localhost swagger]# mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /opt/maven
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-514.26.2.el7.x86_64", arch: "amd64", family: "unix"
[root@localhost swagger]# ls
editor  editor.sh  inflector.yaml  pom.xml  src

**Comment by fehguy** [comment]
Looks like maven central was down, or your firewall rules aren't letting you access it.

```
Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.180.215] failed
```

Is your boogey man.

**Comment by bruceforlearn** [comment]
@fehguy thank you, sir !
I run Jetty Server successfully
