### ISSUE TITLE
Operations with white space 

### ISSUE THREAD

**Issue by monestri** [swagger-api/swagger-inflector#23]
SwaggerOperationsController will try to find classes with white space if the underlying operation has white space. I would suggest trimming all white space from the operation name when trying to search for a class, or replacing with underscore.

**Comment by monestri** [comment]
Not sure this addresses the issue. 

The bug appears to be in here:
io.swagger.inflector.utils.ReflectionUtils.getControllerName(Operation)

This can return:
com.foo.bar.fakedata.controllers.Object Type

Which triggers:
LOGGER.debug("didn't find class " + controller);

**Comment by fehguy** [comment]
Got it.  Yes, the method name has been sanitized, but not the controller name.  I'll apply the same logic there.
