### ISSUE TITLE
Failing JUnit tests

### ISSUE THREAD

**Issue by joeljons** [swagger-api/swagger-inflector#243]
Mostly TestNG is used in this project. There are however three containing tests annotated with `@org.junit.Test`. I had the confusing situation that those tests are ran on one of two computers when executing `mvn clean test`.

* BodyParamExctractionTest, *contains a failing test*
* ResponseModelTest
* PrimitiveResponseTestIT

I suggest all should be changed to TestNG tests, but the failing test needs to be fixed when doing this.

**Comment by gracekarina** [comment]
Hi, @joeljons I've merge the fix, I'm closing issue, please reopen if it keeps happening.
Thanks!
