### ISSUE TITLE
POST requests with root array data fails to deserialize

### ISSUE THREAD

**Issue by monestri** [swagger-api/swagger-inflector#27]
When making post requests where a parameter contains an array of objects at the root, inflector does not deserialize as expected. The method receives a `List<LinkedHashMap>`, instead of `List<ObjectFilter>`. 

```
 /object_search:
    post:
      parameters:
        - name: object_filters
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/Object_Filter'
        - name: duration_seconds
          in: query
          type: integer
          format: int64
        - name: start_time_seconds
          in: query
          type: integer
          format: int64
      responses:
        200:
          schema:
            $ref: '#/definitions/Search_Response'
```

The first step to fixing this issue might be to use the correct class when deserializing with jackson. In io.swagger.inflector.processors.EntityProcessorFactory.readValue(), if class parameter is set to io.swagger.client.model.ObjectFilter[] instead of java.util.List, the serialization should occur correctly. Using something like this might do the trick:

```
class1 = Class.forName("[Lio.swagger.client.model.ObjectFilter;");
```
The proper classname to get should be available via the model mappings. I got stuck moving forward after this, because SwaggerOperationController will fail now to invoke any of my methods. The only workaround I can think of at the moment would be to put the array in a wrapper object.

**Comment by webron** [comment]
Since you talked online, I'm sure @fehguy knows what you mean but...

> The method receives a List, instead of List. 

Care to clarify that statement? :)

**Comment by fehguy** [comment]
@webron i updated his comment, there were some brackets which were getting ignored by the HTML renderer

**Comment by monestri** [comment]
https://github.com/monestri/swagger-inflector/commit/e9dbc615d243058efbed672d79ad64a261ae2d72

Possible fix.. code is not elegant, but I might use this while until a proper fix is available.

**Comment by fehguy** [comment]
The PR #32 addresses the root issue.  The only notable difference as a consumer is that for body inputs defined as `array`, the code will look to match with `Array` java types, as opposed to `List<?>`, which must be untyped due to erasure.  I think this is a better, typesafe solution.  @monestri would live you input.

**Comment by fehguy** [comment]
I'm going to merge the PR but keep the issue open.  Since we're still in preview state, making changes to the expected signatures is acceptable

**Comment by monestri** [comment]
Changes seem okay. A few comments:

1. Inflector still successfully matches against List<?>, but later throws an argument mismatch exception on execution. The initial start should no longer match against List<?> at all. 
2. It was nice being able to copy the output of "looking for operation..." into eclipse to write code. This is no longer quite as easy now that the method signature is printed out as " [array type, component type: [simple type, class io.swagger.client.model.ObjectFilter]] object_filters"

**Comment by fehguy** [comment]
This should be fixed, please reopen if not!
