### ISSUE TITLE
AnonymousModel tag returned from XmlExampleSerializer 

### ISSUE THREAD

**Issue by richard-walsh-sb** [swagger-api/swagger-inflector#369]
When serializing fully resolved OpenAPI example which contains an object of type array with `allOf` and `$ref` using `XmlExampleSerializer` the result contains `<AnonymousModel>` tag. I have pushed a unit test which demonstrates this behavior here -> https://github.com/swagger-api/swagger-inflector/pull/368

**Comment by richard-walsh-sb** [comment]
FYI  in case its not clear, the test I added is passing but contains the `AnonymousModel` in the assertion

**Comment by gracekarina** [comment]
This issue has been closed by:
https://github.com/swagger-api/swagger-parser/pull/1578
https://github.com/swagger-api/swagger-inflector/pull/399
