### ISSUE TITLE
support x-hidden on operations, parameters, model properties

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-inflector#46]

**Comment by olensmar** [comment]
I suggest we prefix all inflector extensions with "x-inflector" instead of just "x"

**Comment by fehguy** [comment]
Sure, that makes sense.

**Comment by olensmar** [comment]
@fehguy what were you thinking here? Should hidden objects get filtered out when serving up the swagger definition?

**Comment by fehguy** [comment]
My thought is that we add a default implementation of 'SpecFilter' which filters away the hidden components

**Comment by olensmar** [comment]
ok got it - i'll do this if you don't get to it first :-)

**Comment by fehguy** [comment]
added with https://github.com/swagger-api/swagger-inflector/commit/6a3348cb110f422d1465d4ca595896e3f86ea1b7
