### ISSUE TITLE
RequestContext is required?

### ISSUE THREAD

**Issue by atdiff** [swagger-api/swagger-inflector#73]
Based on my initial work with swagger-inflector, it appears that the RequestContext is required in the methods of the controller.  Is that correct and is there a reason for it?  The reason I question it is that it seems like a forced implementation for anyone that wants to use it.  Not knowing much about the specifics, conceptually, it'd be nice if it were a little freer to allow other objects - similar to how the response allows a variety of objects to be returned.

**Comment by fehguy** [comment]
Yes, it is required.  That is the holder of the context of the incoming request, which is necessary for getting headers, supported media types, etc.  If you don't like having it as an argument for the method, you can always use a DI framework.

**Comment by atdiff** [comment]
Ah, thanks for the info.  I figured it was something like that.

Are there some examples of how to set it up with a DI framework?  Or some sample projects that are using it currently?

**Comment by olensmar** [comment]
Hi - we use the inflector internally with DropWizard and Guice as our DI framework - I can try to create a sample if that setup is of interest?

**Comment by atdiff** [comment]
@olensmar that would be awesome if you don't mind!

**Comment by olensmar** [comment]
i'll do it - but not before next week - sorry to keep you waiting :-)

**Comment by atdiff** [comment]
No worries. Thanks!

**Comment by olensmar** [comment]
just created a PR for this at https://github.com/swagger-api/swagger-samples/pull/47 - let me know if you have any questions!
