### ISSUE TITLE
Payload validation - recursive schema issue

### ISSUE THREAD

**Issue by mbyst** [swagger-api/swagger-inflector#84]
It appears the validation of payloads defined using recursive schemas do not work well. With recursive schema I mean a tree structure, where an object of a given type contains a property (child) of same type. E.g. an instance of object of type Directory, representing a directory of a file system, may contain a nested structure of subdirectories, which are of the same type Directory.
It the method io.swagger.inflector.utils.ResolverUtil.resolveFully(Swagger swagger) is called for such a swagger definition with recursive schema, it fails with java.lang.StackOverflowError in an infinite loop.

**Comment by webron** [comment]
Can you submit a PR for this?

**Comment by fehguy** [comment]
Please test from master.  I believe this is resolved.

**Comment by mbyst** [comment]
Hi, the bug was fixed only partially. I am still getting StackOverflowError with the following API definition:
{
  "swagger": "2.0",
  "paths": {
    "/methodA": {
      "post": {
        "parameters": [{
          "in": "body",
          "name": "body",
          "schema": {
            "$ref": "#/definitions/ModelA"
          }
        }]
      }
    },
    "/methodB": {
      "put": {
        "parameters": [{
          "in": "body",
          "name": "body",
          "schema": {
            "$ref": "#/definitions/ModelA"
          }
        }]
      }
    }
  },
  "definitions": {
    "ModelA": {
      "type": "object",
      "properties": {
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ModelA"
          }
        }
      }
    }
  }
}
Thanks.

**Comment by mbyst** [comment]
It appears the ResolverUtil class was fixed. However, if I try to get the JSON Schema for a given model, I get again an StackOverflowError, but now it happens on a different location. Could you please try to analyze this problem too? It can be reproduced for your test case io.swagger.test.utils.ResolverUtilTest.testSelfReferenceResolution()

Just add the following lines to the end of the method:
       		
        Parameter param = swagger.getPaths().get("/selfRefB").getGet().getParameters().get(0);
        BodyParameter bp = (BodyParameter) param;
        Model schema = bp.getSchema();
        String jsonSchema = Json.pretty(schema);
        System.out.println(jsonSchema);

Thanks.

**Comment by mbyst** [comment]
FYI: I opened an issue #91 some time ago, which  addresses the same problem.
