### ISSUE TITLE
Invalid schema dereferencing while request payload is being validated

### ISSUE THREAD

**Issue by mbyst** [swagger-api/swagger-inflector#85]
If an API method definition contains a request payload and the schema is referenced by $ref keyword, subschemas are not resolved correctly.

Example:
Given a method with request payload
```json
"paths" : {
    "/test/method" : {
      "post" : {
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/StructureA"
          }
        } ],
```

And definitions section containing following types:
```json
  "definitions" : {
    "StructureA" : {
      "type" : "object",
      "properties" : {
        "someProperty" : {
          "type" : "string"
        },
        "arrayOfOtherType" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/StructureB"
          }
        }
      },
    "StructureB" : {
      "type" : "object",
      "properties" : {
        "someProperty" : {
          "type" : "string"
        }
      }
```
If request is being validated, the schema is not correctly resolved - StructureB is not dereferenced and thus the validation does not work well. The issue is in class io.swagger.inflector.utils.ResolverUtil, namely in method "public Model resolveFully(Model schema)". The if statement if(schema instanceof RefModel) cannot directly return resolved model - if it is an instance of ModelImpl, it must be additionaly recursively resolved.

**Comment by webron** [comment]
Can you submit a PR for it?
