### ISSUE TITLE
Payload validation does not work for recursive schema

### ISSUE THREAD

**Issue by mbyst** [swagger-api/swagger-inflector#91]
Given the following sample swagger definition:
```
swagger: '2.0'
paths:
  /selfRefA:
    post:
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/ModelA'
definitions:
  ModelA:
    properties:
      modelA:
        $ref: '#/definitions/ModelA'";
```

Pyload validation for this definition fails, because of StackOverflowError. The cause of this error is actually an infinite loop arised during the serialization of the payload model to JSON schema - calling Json.pretty(Object) in io.swagger.inflector.controllers.SwaggerOperationController.(Object, Model, SchemaValidator.Direction) method.
I guess either a custom Jackson serializer is needed for correct JSON serialization or another approach for model resolution (ResolverUtil.resolveFully(Swagger)).

**Comment by mbyst** [comment]
Attaching a test case.
[ResolverUtilRecursiveTest.zip](https://github.com/swagger-api/swagger-inflector/files/150983/ResolverUtilRecursiveTest.zip)

**Comment by fehguy** [comment]
This should be fixed with master. If the scheme is recursive, it is likely that nested values cannot be resolved and validated. Please test and report back with any issues
