### ISSUE TITLE
NPE after inheriting DefaultSpecFilter from AbstractSpecFiltrer

### ISSUE THREAD

**Issue by Kvezon** [swagger-api/swagger-inflector#92]
> ERROR [2016-03-09 16:12:45,223] io.swagger.inflector.utils.DefaultExceptionMapper: There was an error processing your request. It has been logged (ID: 1a911a12a64bd0b0).
! java.lang.NullPointerException: null
! at io.swagger.core.filter.SpecFilter.locateNestedReferencedDefinitions(SpecFilter.java:173) ~[swagger-core-1.5.7.jar:1.5.7]
! at io.swagger.core.filter.SpecFilter.removeBrokenReferenceDefinitions(SpecFilter.java:163) ~[swagger-core-1.5.7.jar:1.5.7]
! at io.swagger.core.filter.SpecFilter.filter(SpecFilter.java:94) ~[swagger-core-1.5.7.jar:1.5.7]
! at io.swagger.inflector.controllers.SwaggerResourceController.apply(SwaggerResourceController.java:53) ~[classes/:na]
! at io.swagger.inflector.controllers.SwaggerResourceController.apply(SwaggerResourceController.java:32) ~[classes/:na]

**Comment by fehguy** [comment]
This has been fixed
